Freeze Sphinx version < 1.7 ATM
This is due to the issue in https://github.com/Syntaf/travis-sphinx/issues/34
Error message is:
AttributeError: 'module' object has no attribute 'build_main'